# Executable Paths
PYTHON_EXEC="python3"
JULIA_EXEC="julia"
MATLAB_EXEC="/Applications/MATLAB_R2024a.app/bin/matlab"

# SCRIPT PATHS
PYTHON_SCRIPT="/Users/elinarezaeian/PycharmProjects/HDF5Project/Main.py"
JULIA_SCRIPT="/Users/elinarezaeian/Julia/Julia0.jl"
MATLAB_SCRIPT="/Users/elinarezaeian/MATLAB/Projects/MainProject/"
MATLAB_DIR="/Users/elinarezaeian/MATLAB/Projects/MainProject/"


# Arguments
FILENAME="/Users/elinarezaeian/PycharmProjects/HDF5Project/example.mat"
DATA_DICT='{"string_data": "example_string", "float_data": 3.141592653589793, "int8_data": 42, "uint8_data": 255, "int16_data": 32767, "uint16_data": 65535, "int32_data": 2147483647, "uint32_data": 4294967295, "int64_data": 9223372036854775807, "uint64_data": 18446744073709551615, "float32_data": 3.14159, "float16_data": 3.14, "bool_data": true, "char_data": "a", "complex_data": "3+4j", "decimal_data": "3.1415926535897932384626433832795028841971", "fraction_data": "22/7", "bigint_data": "123456789123456789123456789", "nan_data": "NaN", "duration_data": 1.5, "datetime_data": "2024-07-30T12:34:56"}'

# String
STRING_VALUE="example_string"
# Float
FLOAT_VALUE=3.141592653589793
# int8
INT8_VALUE=42
# uint8
UINT8_VALUE=255
# int16
INT16_VALUE=32767
# uint16
UINT16_VALUE=65535
# int32
INT32_VALUE=2147483647
# uint32
UINT32_VALUE=4294967295
# int64
INT64_VALUE=9223372036854775807
# uint64
UINT64_VALUE=18446744073709551615
# int128
INT128_VALUE=170141183460469231731687303715884105727
# uint128
UINT128_VALUE=340282366920938463463374607431768211455
## float16
FLOAT16_VALUE=3.14
# single / float32 / Float32
FLOAT32_VALUE=3.14159
# logical / bool / Bool
BOOL_VALUE=true
# char
CHAR_VALUE='a'
## complex
COMPLEX_VALUE='3+4j'
# decimal
DECIMAL_VALUE=3.1415926535897932384626433832795028841971
# fraction
FRACTION_VALUE=22/7
# BigInt
BIGINT_VALUE=123456789123456789123456789
# NaN
NAN_VALUE="NaN"
# duration / timedelta
DURATION_VALUE=1.5  # seconds
# datetime
DATETIME_VALUE="2024-07-30T12:34:56"
#echo "--------------------------------"


echo "Python-Python"
$PYTHON_EXEC $PYTHON_SCRIPT selfTesting $FILENAME $STRING_VALUE $FLOAT_VALUE $INT8_VALUE $UINT8_VALUE $INT16_VALUE $UINT16_VALUE $INT32_VALUE $UINT32_VALUE $INT64_VALUE $UINT64_VALUE $FLOAT16_VALUE $FLOAT32_VALUE $BOOL_VALUE $CHAR_VALUE $COMPLEX_VALUE $DECIMAL_VALUE $FRACTION_VALUE $BIGINT_VALUE $NAN_VALUE  $DURATION_VALUE $DATETIME_VALUE
echo "--------------------------------"

echo "Julia-Julia"
$JULIA_EXEC  $JULIA_SCRIPT selfTesting $FILENAME $STRING_VALUE $FLOAT_VALUE $INT8_VALUE $UINT8_VALUE $INT16_VALUE $UINT16_VALUE $INT32_VALUE $UINT32_VALUE $INT64_VALUE $UINT64_VALUE $INT128_VALUE $UINT128_VALUE $FLOAT16_VALUE $FLOAT32_VALUE $BOOL_VALUE $CHAR_VALUE $COMPLEX_VALUE $DECIMAL_VALUE $FRACTION_VALUE $BIGINT_VALUE $NAN_VALUE  $DURATION_VALUE $DATETIME_VALUE
echo "--------------------------------"

echo "MATLAB-MATLAB"
# change the current working directory to the directory specified by the $MATLAB_SCRIPT
cd $MATLAB_DIR
$MATLAB_EXEC -batch "Main('selfTesting', '$FILENAME', '$STRING_VALUE', $FLOAT_VALUE, $INT8_VALUE, $UINT8_VALUE, $INT16_VALUE, $UINT16_VALUE, $INT32_VALUE, $UINT32_VALUE, $INT64_VALUE, $UINT64_VALUE, $FLOAT16_VALUE, $FLOAT32_VALUE, $BOOL_VALUE, '$CHAR_VALUE', $COMPLEX_VALUE, '$DECIMAL_VALUE', '$FRACTION_VALUE', '$BIGINT_VALUE', $NAN_VALUE, $DURATION_VALUE, '$DATETIME_VALUE'); exit;" 2>/dev/null
echo "--------------------------------"

echo "Python-MATLAB:"
$PYTHON_EXEC $PYTHON_SCRIPT serializing_Py $FILENAME "$DATA_DICT"
cd $MATLAB_DIR
$MATLAB_EXEC -batch "Main('deserializeSerialize_data', '$FILENAME', '$STRING_VALUE', $FLOAT_VALUE, $INT8_VALUE, $UINT8_VALUE, $INT16_VALUE, $UINT16_VALUE, $INT32_VALUE, $UINT32_VALUE, $INT64_VALUE, $UINT64_VALUE, $FLOAT16_VALUE, $FLOAT32_VALUE, $BOOL_VALUE, '$CHAR_VALUE', $COMPLEX_VALUE, '$DECIMAL_VALUE', '$FRACTION_VALUE', '$BIGINT_VALUE', $NAN_VALUE, $DURATION_VALUE, '$DATETIME_VALUE'); exit;" 2>/dev/null
$PYTHON_EXEC $PYTHON_SCRIPT deserializing_Py $FILENAME $STRING_VALUE $FLOAT_VALUE $INT8_VALUE $UINT8_VALUE $INT16_VALUE $UINT16_VALUE $INT32_VALUE $UINT32_VALUE $INT64_VALUE $UINT64_VALUE $FLOAT16_VALUE $FLOAT32_VALUE $BOOL_VALUE $CHAR_VALUE $COMPLEX_VALUE $DECIMAL_VALUE $FRACTION_VALUE $BIGINT_VALUE $NAN_VALUE  $DURATION_VALUE $DATETIME_VALUE
echo "--------------------------------"

echo "MATLAB-Python"
cd $MATLAB_DIR
$MATLAB_EXEC -batch "Main('serialize_data', '$FILENAME', '$DATA_DICT'); exit;" 2>/dev/null
$PYTHON_EXEC $PYTHON_SCRIPT deserializingSerializing_Py $FILENAME $STRING_VALUE $FLOAT_VALUE $INT8_VALUE $UINT8_VALUE $INT16_VALUE $UINT16_VALUE $INT32_VALUE $UINT32_VALUE $INT64_VALUE $UINT64_VALUE $FLOAT16_VALUE $FLOAT32_VALUE $BOOL_VALUE $CHAR_VALUE $COMPLEX_VALUE $DECIMAL_VALUE $FRACTION_VALUE $BIGINT_VALUE  $NAN_VALUE  $DURATION_VALUE $DATETIME_VALUE
cd $MATLAB_DIR
$MATLAB_EXEC -batch "Main('deserialize_data', '$FILENAME', '$STRING_VALUE', $FLOAT_VALUE, $INT8_VALUE, $UINT8_VALUE, $INT16_VALUE, $UINT16_VALUE, $INT32_VALUE, $UINT32_VALUE, $INT64_VALUE, $UINT64_VALUE, $FLOAT16_VALUE, $FLOAT32_VALUE, $BOOL_VALUE, '$CHAR_VALUE', $COMPLEX_VALUE, '$DECIMAL_VALUE', '$FRACTION_VALUE', '$BIGINT_VALUE', $NAN_VALUE, $DURATION_VALUE, '$DATETIME_VALUE'); exit;" 2>/dev/null
echo "--------------------------------"

echo "Python-Julia"
$PYTHON_EXEC $PYTHON_SCRIPT serializing_Py $FILENAME "$DATA_DICT"
$JULIA_EXEC  $JULIA_SCRIPT deserializeSerialize_data $FILENAME $STRING_VALUE $FLOAT_VALUE $INT8_VALUE $UINT8_VALUE $INT16_VALUE $UINT16_VALUE $INT32_VALUE $UINT32_VALUE $INT64_VALUE $UINT64_VALUE $FLOAT16_VALUE $FLOAT32_VALUE $BOOL_VALUE $CHAR_VALUE $COMPLEX_VALUE $DECIMAL_VALUE $FRACTION_VALUE $BIGINT_VALUE  $NAN_VALUE $DURATION_VALUE $DATETIME_VALUE
$PYTHON_EXEC $PYTHON_SCRIPT deserializing_Py $FILENAME $STRING_VALUE $FLOAT_VALUE $INT8_VALUE $UINT8_VALUE $INT16_VALUE $UINT16_VALUE $INT32_VALUE $UINT32_VALUE $INT64_VALUE $UINT64_VALUE $FLOAT16_VALUE $FLOAT32_VALUE $BOOL_VALUE $CHAR_VALUE $COMPLEX_VALUE $DECIMAL_VALUE $FRACTION_VALUE $BIGINT_VALUE  $NAN_VALUE $DURATION_VALUE $DATETIME_VALUE
echo "--------------------------------"

echo "Julia-Python"
$JULIA_EXEC  $JULIA_SCRIPT serialize_data $FILENAME "$DATA_DICT"
$PYTHON_EXEC $PYTHON_SCRIPT deserializingSerializing_Py $FILENAME $STRING_VALUE $FLOAT_VALUE $INT8_VALUE $UINT8_VALUE $INT16_VALUE $UINT16_VALUE $INT32_VALUE $UINT32_VALUE $INT64_VALUE $UINT64_VALUE $FLOAT16_VALUE $FLOAT32_VALUE $BOOL_VALUE $CHAR_VALUE $COMPLEX_VALUE $DECIMAL_VALUE $FRACTION_VALUE $BIGINT_VALUE $NAN_VALUE $DURATION_VALUE $DATETIME_VALUE
$JULIA_EXEC  $JULIA_SCRIPT deserialize_data $FILENAME $STRING_VALUE $FLOAT_VALUE $INT8_VALUE $UINT8_VALUE $INT16_VALUE $UINT16_VALUE $INT32_VALUE $UINT32_VALUE $INT64_VALUE $UINT64_VALUE $FLOAT16_VALUE $FLOAT32_VALUE $BOOL_VALUE $CHAR_VALUE $COMPLEX_VALUE $DECIMAL_VALUE $FRACTION_VALUE $BIGINT_VALUE $NAN_VALUE $DURATION_VALUE $DATETIME_VALUE
echo "--------------------------------"

echo "MATLAB-Julia"
cd $MATLAB_DIR
$MATLAB_EXEC -batch "Main('serialize_data', '$FILENAME', '$DATA_DICT'); exit;" 2>/dev/null
$JULIA_EXEC  $JULIA_SCRIPT deserializeSerialize_data $FILENAME $STRING_VALUE $FLOAT_VALUE $INT8_VALUE $UINT8_VALUE $INT16_VALUE $UINT16_VALUE $INT32_VALUE $UINT32_VALUE $INT64_VALUE $UINT64_VALUE $FLOAT16_VALUE $FLOAT32_VALUE $BOOL_VALUE $CHAR_VALUE $COMPLEX_VALUE $DECIMAL_VALUE $FRACTION_VALUE $BIGINT_VALUE $NAN_VALUE $DURATION_VALUE $DATETIME_VALUE
cd $MATLAB_DIR
$MATLAB_EXEC -batch "Main('deserialize_data', '$FILENAME', '$STRING_VALUE', $FLOAT_VALUE, $INT8_VALUE, $UINT8_VALUE, $INT16_VALUE, $UINT16_VALUE, $INT32_VALUE, $UINT32_VALUE, $INT64_VALUE, $UINT64_VALUE, $FLOAT16_VALUE, $FLOAT32_VALUE, $BOOL_VALUE, '$CHAR_VALUE', $COMPLEX_VALUE, '$DECIMAL_VALUE', '$FRACTION_VALUE', '$BIGINT_VALUE', $NAN_VALUE, $DURATION_VALUE, '$DATETIME_VALUE'); exit;" 2>/dev/null
echo "--------------------------------"

echo "Julia-MATLAB"
$JULIA_EXEC  $JULIA_SCRIPT serialize_data $FILENAME "$DATA_DICT"
cd $MATLAB_DIR
$MATLAB_EXEC -batch "Main('deserializeSerialize_data', '$FILENAME', '$STRING_VALUE', $FLOAT_VALUE, $INT8_VALUE, $UINT8_VALUE, $INT16_VALUE, $UINT16_VALUE, $INT32_VALUE, $UINT32_VALUE, $INT64_VALUE, $UINT64_VALUE, $FLOAT16_VALUE, $FLOAT32_VALUE, $BOOL_VALUE, '$CHAR_VALUE', $COMPLEX_VALUE, '$DECIMAL_VALUE', '$FRACTION_VALUE', '$BIGINT_VALUE', $NAN_VALUE, $DURATION_VALUE, '$DATETIME_VALUE'); exit;" 2>/dev/null
$JULIA_EXEC  $JULIA_SCRIPT deserialize_data $FILENAME $STRING_VALUE $FLOAT_VALUE $INT8_VALUE $UINT8_VALUE $INT16_VALUE $UINT16_VALUE $INT32_VALUE $UINT32_VALUE $INT64_VALUE $UINT64_VALUE $FLOAT16_VALUE $FLOAT32_VALUE $BOOL_VALUE $CHAR_VALUE $COMPLEX_VALUE $DECIMAL_VALUE $FRACTION_VALUE $BIGINT_VALUE $NAN_VALUE $DURATION_VALUE $DATETIME_VALUE
echo "--------------------------------"

# chmod +x /Users/elinarezaeian/PycharmProjects/HDF5-Testing/run.sh
# /Users/elinarezaeian/PycharmProjects/HDF5-Testing/run.sh
